# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Detection algorithm using C++
#'
#' @param v an initial numeric data and beta a penalization parameter
#' @return a sorted vector
#' @export
OP_Rcpp <- function(v, beta) {
    .Call(`_Firstep_OP_Rcpp`, v, beta)
}

#' Heap sort algorithm using C++
#'
#' @param v an initial numeric data and beta a penalization parameter
#' @return a sorted vector
#' @export
PELT_Rcpp <- function(v, beta) {
  .Call(`_Firstep_heap_sort_Rcpp`, v, beta)
}


